// examples/kit-nextjs-article-starter/src/components/sxa/Container.tsx
import React, { JSX } from 'react';
import {
  ComponentParams,
  ComponentRendering,
  AppPlaceholder,
} from '@sitecore-content-sdk/nextjs';
import componentMap from '.sitecore/component-map';
import { ComponentProps } from 'lib/component-props';

interface ContainerProps extends ComponentProps {
  rendering: ComponentRendering & { params: ComponentParams };
  params: ComponentParams;
}

const DefaultContainer = (props: ContainerProps): JSX.Element => {
  const containerStyles =
    props.params && props.params.Styles ? props.params.Styles : '';
  const styles = `${props.params?.GridParameters || ''} ${containerStyles}`.trimEnd();
  const phKey = `container-${props.params.DynamicPlaceholderId}`;
  const id = props.params.RenderingIdentifier;
  const mediaUrlPattern = new RegExp(/mediaurl=\"([^"]*)\"/, 'i');
  const backgroundImage = props.params.BackgroundImage as string;
  let backgroundStyle: { [key: string]: string } = {};

  if (backgroundImage && backgroundImage.match(mediaUrlPattern)) {
    const mediaUrl = backgroundImage.match(mediaUrlPattern)?.[1] || '';

    backgroundStyle = {
      backgroundImage: `url('${mediaUrl}')`,
    };
  }

  return (
    <div
      className={`component container-default ${styles}`}
      id={id ? id : undefined}
    >
      <div className="component-content" style={backgroundStyle}>
        <div className="row">
          <AppPlaceholder
            name={phKey}
            rendering={props.rendering}
            page={props.page}
            componentMap={componentMap}
          />
        </div>
      </div>
    </div>
  );
};

export const Default = ({
  params,
  rendering,
  page,
}: ContainerProps): JSX.Element => {
  const splitStyles = params?.Styles?.split(' ');

  if (splitStyles && splitStyles.includes('container')) {
    return (
      <div className="container-wrapper">
        <DefaultContainer params={params} rendering={rendering} page={page} />
      </div>
    );
  }

  return <DefaultContainer params={params} rendering={rendering} page={page} />;
};

// examples/basic-spa/src/app/components/container.component.ts
import { Component, computed, input } from '@angular/core';
import { ComponentRendering, ScPlaceholderComponent } from '@sitecore-content-sdk/angular';
import { sxaComponentClass, sxaRenderingId, sxaStyles, type SxaParams } from './sxa-params';

const MEDIA_URL_PATTERN = /mediaurl="([^"]*)"/i;

@Component({
  selector: 'app-container',
  imports: [ScPlaceholderComponent],
  template: `
    <div [class.container-wrapper]="wrapInContainer()">
      <div class="{{ componentClass() }}" [attr.id]="renderingId()">
        <div class="component-content" [style.background-image]="backgroundImage()">
          <div class="row">
            @if (rendering(); as renderingValue) {
              <sc-placeholder
                class="row"
                [name]="placeholderName()"
                [rendering]="renderingValue"
              ></sc-placeholder>
            }
          </div>
        </div>
      </div>
    </div>
  `,
})
export class ContainerComponent {
  readonly fields = input<{ [key: string]: unknown }>({});
  readonly params = input<SxaParams>({});
  readonly rendering = input<ComponentRendering>();

  readonly componentClass = computed(() =>
    sxaComponentClass('component container-default', this.params())
  );
  readonly renderingId = computed(() => sxaRenderingId(this.params()));
  readonly wrapInContainer = computed(() => sxaStyles(this.params()).split(/\s+/).includes('container'));
  readonly placeholderName = computed(() => {
    const id = this.params().DynamicPlaceholderId || this.rendering()?.params?.DynamicPlaceholderId;
    return id ? `container-${id}` : 'container';
  });
  readonly backgroundImage = computed(() => {
    const raw = this.params().BackgroundImage || this.rendering()?.params?.BackgroundImage;
    if (!raw) return undefined;
    const match = raw.match(MEDIA_URL_PATTERN);
    const url = match?.[1];
    return url ? `url('${url}')` : undefined;
  });
}

export default ContainerComponent;
export { ContainerComponent as Default };
